### PR TITLE
Override prefix and destdir

### PR DESCRIPTION
**Pull request by wsakernel**
I wanted to be able to override PREFIX, so Debian could remove the only patch they had for egctl. Then I found https://github.com/edeX-UG/egctl which already did the same and had IMO nice README improvements as well. So, I added overriding DESTDIR as well and now forward these patches. I hope you like them.

### CODE REVIEW

**Comment by unterwulf** [comment]
Declaring these variables as overridable from the environment doesn't look like a good practice to me (even GNU make manual doesn't recommend doing so). Instead of making a patch the Debian maintainer should've probaly read Debian's documentation on how to properly override such variables (https://www.debian.org/doc/manuals/debmake-doc/ch04.en.html#step-maintainer). Interestingly enough, in the Makefile from Debian's example the variable `prefix` is defined as `prefix = /usr/local`, not `prefix ?= /usr/local`.

I'm not sure about your use case, but why don't you just use `make PREFIX=/prefix DESTDIR=/destdir`?

If you still need to inherit these values from the environment you can build egctl using `make PREFIX=$PREFIX DESTDIR=$DESTDIR` without patching anything.

**Comment by wsakernel** [comment]
Point taken. I will check with Debian to remove their patch. Thanks for the pointers. Shall I update the README updates from patch 2 accordingly or don't you like them at all?

**Comment by unterwulf** [comment]
The README file has been updated in 6ee6e3da0a31ee1a293fd2066adb75cf35055ec0. Hopefully, now maintainers don't have to look into Makefile at all :-)

**Comment by wsakernel** [comment]
Cool. I'll open a ticket in Debian, point them to the new version with a comment to drop their patch. Thanks for your help!

**Pull request closed without merging**
